table dim_sessao
	lineageTag: d440a3c5-d37f-4371-910e-6bda9c4120c3

	measure Sessões = DISTINCTCOUNT ( dim_sessao[sessao_id] )
		formatString: 0
		displayFolder: Sessões

	measure 'Duração média da sessão' = AVERAGE ( dim_sessao[duracao_minutos] )
		formatString: #,0 "min"
		displayFolder: Sessões

	column sessao_id
		dataType: string
		lineageTag: 9d1f2749-38bc-4a36-9ead-3537ca9ebbbd
		summarizeBy: none
		sourceColumn: sessao_id

		annotation SummarizationSetBy = Automatic

	column perfil
		dataType: string
		lineageTag: ef0b885a-7457-4e5f-861d-3c143dc3fc2c
		summarizeBy: none
		sourceColumn: perfil

		annotation SummarizationSetBy = Automatic

	column duracao_minutos
		dataType: int64
		formatString: 0
		lineageTag: 1aa06e9d-91c7-4f2e-a13a-f1053882371b
		summarizeBy: sum
		sourceColumn: duracao_minutos

		annotation SummarizationSetBy = Automatic

	column duracao_horas
		dataType: double
		lineageTag: 2e4b2fdc-00fd-473e-ab43-af7623e4c0ec
		summarizeBy: sum
		sourceColumn: duracao_horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_sessao = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents(PastaDados & "\uodly_powerbi.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "dim_sessao", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"sessao_id", type text}, {"perfil", type text}, {"duracao_minutos", Int64.Type}, {"duracao_horas", type number}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_ResultType = Table

