table dim_tema
	lineageTag: a05b69f8-43d9-45a4-b140-4ed0e88343ad

	column tema
		dataType: string
		lineageTag: a5080f45-882f-481e-94c6-c39d3750fdc0
		summarizeBy: none
		sourceColumn: tema

		annotation SummarizationSetBy = Automatic

	column severidade
		dataType: int64
		formatString: 0
		lineageTag: 2be6b1ee-95ea-4290-90f4-6eaa41528660
		summarizeBy: none
		sourceColumn: severidade

		annotation SummarizationSetBy = Automatic

	column gravidade
		dataType: string
		lineageTag: 3078399a-dd4a-4ae7-ac5c-b47a4c6b6579
		summarizeBy: none
		sourceColumn: gravidade

		annotation SummarizationSetBy = Automatic

	partition dim_tema = m
		mode: import
		source =
				let
				  Origem = Excel.Workbook(File.Contents(PastaDados & "\uodly_powerbi.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "dim_tema", Kind = "Sheet"]}[Data],
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(#"Navegação 1", [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"tema", type text}, {"severidade", Int64.Type}, {"gravidade", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_ResultType = Table

